#!/bin/sh

dotest "foo=bar; echo \$foo"
dotest "foo=bar; echo \$\$foo"
dotest "foo=bar; echo str\$\$foo"
dotest "foo=bar; echo \$nothing"
dotest "foo=bar; echo \$\$foo\$test"
dotest "foo=bar; echo \$foo\$.foo"
dotest "foo=bar; echo \$\$\$foo\$.foo"
dotest "foo=bar; echo \$.test\$foo\$.foo"
dotest "foo=bar; echo \$\$nothing\$foo\$.foo"

dotest "foo=bar; hello=world; echo \$foo \$hello"
dotest "foo=bar; hello=world; echo \$\$foo \$hello"
dotest "foo=bar; hello=world; echo str\$\$foo \$hello"
dotest "foo=bar; hello=world; echo \$nothing \$hello"
dotest "foo=bar; hello=world; echo \$\$foo\$test \$hello"
dotest "foo=bar; hello=world; echo \$foo\$.foo \$hello"
dotest "foo=bar; hello=world; echo \$\$\$foo\$.foo \$hello"
dotest "foo=bar; hello=world; echo \$.test\$foo\$.foo \$hello"
dotest "foo=bar; hello=world; echo \$\$nothing\$foo\$.foo \$hello"

dotest "foo='ls -la /'; echo \$foo"
dotest "foo='ls -la /'; echo \$\$foo"
dotest "foo='ls -la /'; echo str\$\$foo"
dotest "foo='ls -la /'; echo \$nothing"
dotest "foo='ls -la /'; echo \$\$foo\$test"
dotest "foo='ls -la /'; echo \$foo\$.foo"
dotest "foo='ls -la /'; echo \$\$\$foo\$.foo"
dotest "foo='ls -la /'; echo \$.test\$foo\$.foo"
dotest "foo='ls -la /'; echo \$\$nothing\$foo\$.foo"

dotest "foo='ls -la /'; hello=world; echo \$foo \$hello"
dotest "foo='ls -la /'; hello=world; echo \$\$foo \$hello"
dotest "foo='ls -la /'; hello=world; echo str\$\$foo \$hello"
dotest "foo='ls -la /'; hello=world; echo \$nothing \$hello"
dotest "foo='ls -la /'; hello=world; echo \$\$foo\$test \$hello"
dotest "foo='ls -la /'; hello=world; echo \$foo\$.foo \$hello"
dotest "foo='ls -la /'; hello=world; echo \$\$\$foo\$.foo \$hello"
dotest "foo='ls -la /'; hello=world; echo \$.test\$foo\$.foo \$hello"
dotest "foo='ls -la /'; hello=world; echo \$\$nothing\$foo\$.foo \$hello"

dotest "foo='ls -la /'; hello=world; \$foo \$hello"
dotest "foo='ls -la /'; hello=world; \$\$foo \$hello"
dotest "foo='ls -la /'; hello=world; str\$\$foo \$hello"
dotest "foo='ls -la /'; hello=world; \$nothing \$hello"
dotest "foo='ls -la /'; hello=world; \$\$foo\$test \$hello"
dotest "foo='ls -la /'; hello=world; \$foo\$.foo \$hello"
dotest "foo='ls -la /'; hello=world; \$\$\$foo\$.foo \$hello"
dotest "foo='ls -la /'; hello=world; \$.test\$foo\$.foo \$hello"
dotest "foo='ls -la /'; hello=world; \$\$nothing\$foo\$.foo \$hello"

dotest "foo=bar; hello='ls -la /'; echo \$foo \$hello"
dotest "foo=bar; hello='ls -la /'; echo \$\$foo \$hello"
dotest "foo=bar; hello='ls -la /'; echo str\$\$foo \$hello"
dotest "foo=bar; hello='ls -la /'; echo \$nothing \$hello"
dotest "foo=bar; hello='ls -la /'; echo \$\$foo\$test \$hello"
dotest "foo=bar; hello='ls -la /'; echo \$foo\$.foo \$hello"
dotest "foo=bar; hello='ls -la /'; echo \$\$\$foo\$.foo \$hello"
dotest "foo=bar; hello='ls -la /'; echo \$.test\$foo\$.foo \$hello"
dotest "foo=bar; hello='ls -la /'; echo \$\$nothing\$foo\$.foo \$hello"

dotest "foo='ls -la /'; \$foo"
dotest "foo='ls -la /'; \$\$foo"
dotest "foo='ls -la /'; str\$\$foo"
dotest "foo='ls -la /'; \$nothing"
dotest "foo='ls -la /'; \$\$foo\$test"
dotest "foo='ls -la /'; \$foo\$.foo"
dotest "foo='ls -la /'; \$\$\$foo\$.foo"
dotest "foo='ls -la /'; \$.test\$foo\$.foo"
dotest "foo='ls -la /'; \$\$nothing\$foo\$.foo"

dotest "echo \$USER"
dotest "$USER"
dotest "echo toto\$USERtoto"
dotest "echo \$USER.toto"
dotest "foo=bar; export foo; env | grep ^foo" "foo=bar; setenv foo; env | grep ^foo" 
dotest "foo=bar; export foo; echo \$foo; unset foo; echo \$foo; env | grep ^foo" "foo=bar; setenv foo; echo \$foo; unsetenv foo; echo \$foo; env | grep ^foo"
dotest "export foo=foune; foo=bar; env | grep ^foo" "setenv foo foune; foo=bar; env | grep ^foo"

exit 1
